version: '3.9'
services:
  app:
    container_name: titw_go_server
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - 8001:8080
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - titw

  postgresdb:
    image: postgres:latest
    container_name: titw_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '2345:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - titw

volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  titw:
    driver: bridge