// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Brands                        string
	Currencies                    string
	CurrencyLanguages             string
	ImportJobs                    string
	Languages                     string
	LegalEntityTypes              string
	OrderRows                     string
	Orders                        string
	ProductCategories             string
	ProductCategoryLanguages      string
	ProductItemPrices             string
	ProductItems                  string
	ProductLanguages              string
	ProductPriceMarkup            string
	ProductSpecificationLanguages string
	ProductSpecificationValues    string
	ProductSpecifications         string
	Products                      string
	RefreshTokens                 string
	Suppliers                     string
	Taxes                         string
	UserBillings                  string
	UserPaymentMethods            string
	UserRoleLanguages             string
	UserRoles                     string
	Users                         string
	VehicleTypeLanguages          string
	VehicleTypes                  string
}{
	Brands:                        "brands",
	Currencies:                    "currencies",
	CurrencyLanguages:             "currency_languages",
	ImportJobs:                    "import_jobs",
	Languages:                     "languages",
	LegalEntityTypes:              "legal_entity_types",
	OrderRows:                     "order_rows",
	Orders:                        "orders",
	ProductCategories:             "product_categories",
	ProductCategoryLanguages:      "product_category_languages",
	ProductItemPrices:             "product_item_prices",
	ProductItems:                  "product_items",
	ProductLanguages:              "product_languages",
	ProductPriceMarkup:            "product_price_markup",
	ProductSpecificationLanguages: "product_specification_languages",
	ProductSpecificationValues:    "product_specification_values",
	ProductSpecifications:         "product_specifications",
	Products:                      "products",
	RefreshTokens:                 "refresh_tokens",
	Suppliers:                     "suppliers",
	Taxes:                         "taxes",
	UserBillings:                  "user_billings",
	UserPaymentMethods:            "user_payment_methods",
	UserRoleLanguages:             "user_role_languages",
	UserRoles:                     "user_roles",
	Users:                         "users",
	VehicleTypeLanguages:          "vehicle_type_languages",
	VehicleTypes:                  "vehicle_types",
}
