package eprel

type TyreResponse struct {
	TyreClass                 string      `json:"tyreClass"`
	LoadCapacityIndex         int         `json:"loadCapacityIndex"`
	Status                    string      `json:"status"`
	OtherIdentifiers          interface{} `json:"otherIdentifiers"`
	OnMarketEndDateTS         *int64      `json:"onMarketEndDateTS"`
	EnergyClass               string      `json:"energyClass"`
	OrgVerificationStatus     string      `json:"orgVerificationStatus"`
	SpeedCategorySymbol2      *string     `json:"speedCategorySymbol2"`
	EnergyLabelId             *int        `json:"energyLabelId"`
	DateStartProductionYear   int         `json:"dateStartProductionYear"`
	RimDiameter               int         `json:"rimDiameter"`
	FormType                  string      `json:"formType"`
	OnMarketStartDateTS       int64       `json:"onMarketStartDateTS"`
	ExternalRollingNoiseClass string      `json:"externalRollingNoiseClass"`
	LoadCapacityIndicator     string      `json:"loadCapacityIndicator"`
	ExternalRollingNoiseValue int         `json:"externalRollingNoiseValue"`
	EprelRegistrationNumber   string      `json:"eprelRegistrationNumber"`
	GeneratedLabels           *[]string   `json:"generatedLabels"`
	AdditionalInfos           interface{} `json:"additionalInfos"`
	TyreSection               int         `json:"tyreSection"`
	VisibleToUkMsa            bool        `json:"visibleToUkMsa"`
	CommercialName            string      `json:"commercialName"`
	DateEndProductionWeek     *int        `json:"dateEndProductionWeek"`
	ContactId                 int         `json:"contactId"`
	SizeDesignationFiltered   string      `json:"sizeDesignationFiltered"`
	LastVersion               bool        `json:"lastVersion"`
	AllowEprelLabelGeneration bool        `json:"allowEprelLabelGeneration"`
	AspectRatio               int         `json:"aspectRatio"`
	FirstPublicationDateTS    int64       `json:"firstPublicationDateTS"`
	OnMarketEndDate           *[]int      `json:"onMarketEndDate"`
	SpeedCategorySymbol       string      `json:"speedCategorySymbol"`
	RegistrantNature          string      `json:"registrantNature"`
	TrademarkId               int         `json:"trademarkId"`
	DateEndProductionYear     *int        `json:"dateEndProductionYear"`
	ExportDateTS              int64       `json:"exportDateTS"`
	LoadCapacityIndex3        *int        `json:"loadCapacityIndex3"`
	WetGripClass              string      `json:"wetGripClass"`
	LoadCapacityIndex4        *int        `json:"loadCapacityIndex4"`
	TyreDesignation           string      `json:"tyreDesignation"`
	LoadCapacityIndex2        *int        `json:"loadCapacityIndex2"`
	SizeDesignation           string      `json:"sizeDesignation"`
	OnMarketFirstStartDateTS  int64       `json:"onMarketFirstStartDateTS"`
	DateStartProductionWeek   int         `json:"dateStartProductionWeek"`
	ImplementingAct           string      `json:"implementingAct"`
	Blocked                   bool        `json:"blocked"`
	ModelIdentifier           string      `json:"modelIdentifier"`
	PlacementCountries        interface{} `json:"placementCountries"`
	SkipScaleValidation       bool        `json:"skipScaleValidation"`
	EnergyClassImage          *string     `json:"energyClassImage"`
	VersionId                 int         `json:"versionId"`
	OnMarketFirstStartDate    *[]int      `json:"onMarketFirstStartDate"`
	ProductModelCoreId        int         `json:"productModelCoreId"`
	VersionNumber             int         `json:"versionNumber"`
	UploadedLabels            string      `json:"uploadedLabels"`
	IceTyre                   bool        `json:"iceTyre"`
	SupplierOrTrademark       string      `json:"supplierOrTrademark"`
	ProductGroup              string      `json:"productGroup"`
	SevereSnowTyre            bool        `json:"severeSnowTyre"`
}
