// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserBilling struct {
	UserID            *string `json:"userId"`
	LegalEntityTypeID string  `json:"legalEntityTypeId"`
	Name              string  `json:"name"`
	Surname           string  `json:"surname"`
	FiscalCode        string  `json:"fiscalCode"`
	VatNumber         string  `json:"vatNumber"`
	AddressLine1      string  `json:"addressLine1"`
	AddressLine2      *string `json:"addressLine2"`
	City              string  `json:"city"`
	Province          *string `json:"province"`
	Cap               string  `json:"cap"`
	Country           string  `json:"country"`
}

type LegalEntityType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TaxRate struct {
	ID               string  `json:"id"`
	MarkupPercentage float64 `json:"markupPercentage"`
	Name             string  `json:"name"`
}

type User struct {
	ID          string       `json:"id"`
	Email       string       `json:"email"`
	Username    *string      `json:"username"`
	UserRole    *UserRole    `json:"userRole"`
	UserBilling *UserBilling `json:"userBilling"`
}

type UserBilling struct {
	ID              string           `json:"id"`
	LegalEntityType *LegalEntityType `json:"legalEntityType"`
	TaxRate         *TaxRate         `json:"taxRate"`
	Name            string           `json:"name"`
	Surname         string           `json:"surname"`
	FiscalCode      string           `json:"fiscalCode"`
	VatNumber       string           `json:"vatNumber"`
	AddressLine1    string           `json:"addressLine1"`
	AddressLine2    *string          `json:"addressLine2"`
	City            string           `json:"city"`
	Province        *string          `json:"province"`
	Cap             string           `json:"cap"`
	Country         string           `json:"country"`
	User            *User            `json:"user"`
}

type UserRole struct {
	ID       string `json:"id"`
	RoleCode string `json:"roleCode"`
	Name     string `json:"name"`
	IsAdmin  *bool  `json:"isAdmin"`
}
