package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"pillowww/titw/graph"
	"pillowww/titw/graph/converters"
	"pillowww/titw/graph/model"
	"pillowww/titw/internal/fs/fshandlers"
)

// UserBilling is the resolver for the userBilling field.
func (r *invoiceResolver) UserBilling(ctx context.Context, obj *model.Invoice) (*model.UserBilling, error) {
	ub, err := r.UserDao.FindUserBillingById(ctx, obj.UserBillingId)

	if err != nil {
		return nil, err
	}

	return converters.UserBillingToGraphQL(ub), nil
}

// FileURL is the resolver for the fileUrl field.
func (r *invoiceResolver) FileURL(ctx context.Context, obj *model.Invoice) (string, error) {
	fs := fshandlers.NewInvoiceHandler()

	return fs.GetPublicUrl(obj.FilePath), nil
}

// Invoice returns graph.InvoiceResolver implementation.
func (r *Resolver) Invoice() graph.InvoiceResolver { return &invoiceResolver{r} }

type invoiceResolver struct{ *Resolver }
